require_relative "../lib/tachyon_manifold"

describe TachyonManifold do
  describe "#initialize" do
    it "initializes with input" do
      input = ".......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
..............."
      manifold = TachyonManifold.new(input)
      expect(manifold.split_count).to eq(40)
    end
  end
end
