require_relative "../lib/tachyon_manifold"

describe TachyonManifold do
  describe "#count_splits" do
    it "it correctly counts the splits" do
      input = ".......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
"
      manifold = TachyonManifold.new(input)
      expect(manifold.count_splits).to eq(21)
    end
  end
  describe "#count_all_possible_timelines" do
    it "it correctly counts the splits" do
      input = ".......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
"
      manifold = TachyonManifold.new(input)
      expect(manifold.count_all_possible_timelines).to eq(40)
    end
  end
end
